### ISSUE TITLE
Cannot get slave nodes from metrics

### ISSUE THREAD

**Issue by XZ175411** [ContainerSolutions/locust_exporter#13]
Three workers I have launched, but at metrics I searched 0.

**Comment by pperzyna** [comment]
Could you elaborate a bit more about it?

**Comment by DanTulovsky** [comment]
I have the same problem.

The 'locust_slaves_count' metric is always 0, even with multiple workers running.

**Comment by DanTulovsky** [comment]
Looks like it should be: "locust_workers_count" now. Does the latest image need to be rebuilt?

**Comment by DanTulovsky** [comment]
At https://hub.docker.com/r/containersol/locust_exporter/tags?page=1&ordering=last_updated, the "latest" tag refers to something from a year ago which doesn't have the right fix.

There is a 'master' tag which should have the fix.

As a side note, 'master' should probably be replaced by 'main' for the same reasons 'slave' was replaced by 'worker'.

Would it be possible to update the 'latest' tag to point to the latest image please?

**Comment by DanTulovsky** [comment]
Also, would it be possible to update the dashboard at https://grafana.com/grafana/dashboards/11985 with the latest one from this repo?

Thank you

**Comment by pperzyna** [comment]
@DanTulovsky Thanks for your input. I will rebuild the latest image.

CC: @amouat

**Comment by amouat** [comment]
Let me know if you need any help @pperzyna. We did recently update our Docker Hub account, so you might need new details.

**Comment by max-rocket-internet** [comment]
Any update @pperzyna? I am missing a docker image with the latest code 🙂

**Comment by pperzyna** [comment]
@DanTulovsky & @XZ175411 - Resolved in #20 & #18
