### ISSUE TITLE
Latest release "v0.4.0" not pushed to docker hub

### ISSUE THREAD

**Issue by max-rocket-internet** [ContainerSolutions/locust_exporter#18]
https://hub.docker.com/r/containersol/locust_exporter/tags?page=1&ordering=last_updated

🙂

**Comment by pperzyna** [comment]
Thanks. I am on it

**Comment by pperzyna** [comment]
@max-rocket-internet 

#20 v0.4.1 is available on DockerHub

**Comment by max-rocket-internet** [comment]
Thank you @pperzyna
