### ISSUE TITLE
Feature request: endpoint to gracefully quit the container

### ISSUE THREAD

**Issue by AbdelrhmanHamouda** [ContainerSolutions/locust_exporter#35]
EDIT, updated post from a vague request to a more defined one!

This is a feature request to add a `/quitquitquit` endpoint to the container to exit gracefully. This allows the container to be used as a part of a job/cronJob. This is identical to the `/quitquitquit` exposed by  [istio in v1.3](https://istio.io/latest/news/releases/1.3.x/announcing-1.3/change-notes/#miscellaneous)

**Comment by AbdelrhmanHamouda** [comment]
Hello @pperzyna, is it possible to take a look at this request and share your thoughts?

Thanks in advance,

**Comment by pperzyna** [comment]
@AbdelrhmanHamouda, I am happy to review a PR

**Comment by graipher** [comment]
A quick PR to add that endpoint: https://github.com/ContainerSolutions/locust_exporter/pull/36

**Comment by AbdelrhmanHamouda** [comment]
Hello @pperzyna, it would be much appreciated if the proposed PR can be reviewed (and hopefully merged). For my use case, the proposed changes look like a very nice fit! 

This project is used in my organisation and having this limitation is causing some workarounds to be in place. 

It is not my intention to sound "pushy", however, the current workarounds are "ugly"  and are not "cloud native" which is something i wish we can change soon.  also, thanks @graipher for taking the time to put this PR in place :) 

Thanks in  advance!

**Comment by pperzyna** [comment]
@graipher thank you!
