### ISSUE TITLE
Can't see locust logs 

### ISSUE THREAD

**Issue by johnnashautomation** [ContainerSolutions/locust_exporter#4]
Hello, When I start locust test and open "http://localhost:9646/metrics" I can only see a few logs for locust what would be the problem?

Locust Version 0.14.6

![image](https://user-images.githubusercontent.com/66111402/83406628-bbc9f780-a417-11ea-8464-e4c72c1b5bae.png)

**Comment by robertocpsilva1** [comment]
`locust_up` is 0 which means it's either not running or your exporter instance is not able to scrape from locust. Does the exporter log anything? There's normally a log message when the locust address is wrong or it can't reach it

**Comment by johnnashautomation** [comment]
I got below output in the console log, I don't give 127.0.0.11:53 as static~ anywhere

![image](https://user-images.githubusercontent.com/66111402/83808235-22bc0a80-a6bd-11ea-913e-e81b9cf5994c.png)

**Comment by pperzyna** [comment]
It looks like you are not connected to any locust master.
