### ISSUE TITLE
[Question] What does the new namespace flag does?

### ISSUE THREAD

**Issue by AbdelrhmanHamouda** [ContainerSolutions/locust_exporter#42]
Hello, I see the newly added `namespace` flag however, the documentation is not really helping me understand what does it do. 

can you please shed more light on this and the impact of its use? would be better if this is added to docs as well.

**Comment by pperzyna** [comment]
There is not much difference, as the [default value](https://github.com/ContainerSolutions/locust_exporter/pull/41/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R427) stays the same. **Thanks to the namespace flag, you can change the metrics prefix.** It was also added to [README](https://github.com/ContainerSolutions/locust_exporter/pull/41/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R45)

Closing feel free to open if needed
