### ISSUE TITLE
Connection refused for /metrics endpoint

### ISSUE THREAD

**Issue by phgo** [ContainerSolutions/locust_exporter#8]
Hi there,

I have some trouble getting the locust_exporter to work:
* I have a running Locust test
** http://localhost:8089/ is available
* The exporter is running (?)
> time="2020-09-22T09:41:47Z" level=info msg="Starting locust_exporter (version=, branch=, revision=)" source="main.go:434"
> time="2020-09-22T09:41:47Z" level=info msg="Build context (go=go1.13.8, user=, date=)" source="main.go:435"
> time="2020-09-22T09:41:47Z" level=info msg="Listening on :9646" source="main.go:449"
* http://localhost:9646/metrics gets me "ERR_CONNECTION_REFUSED" (Chrome)
* I explicitly added TCP 9646 to the firewall: same result
* I tried other ports (8081 might be less fishy from the company security perspective): same result
* I tried another PC in another network: same result

Every bit of information that I could find about the locust_exporter just suggests that it works.

Do I oversee something very obvious?

Regards,
Philipp

**Comment by phgo** [comment]
Hi there,

there seems to be an issue with `docker run --net=host ...` for me. If I take the `go run main.go` route, the exporter works like a charm.
So this is probably a configuration issue on my side - perhaps a group policy interfering with the docker network interfaces?!

Regards,
Philipp

**Comment by Spazzy757** [comment]
@phgo If you are using a Mac host network on docker does not work

**Comment by phgo** [comment]
Hi @Spazzy757 ,

thanks for the reply. 
I am not working on Mac though but on a Windows PC which is at least to some extent managed by corporate IT. 

Nevertheless I can work with the exporter now. Actually installing Go on my build agents is even less cumbersome then installing Docker with WSL2. 

Regards,
Philipp
